import type { NextPage } from 'next'
import Head from 'next/head'
import { Footer } from "src/components/templates/footer"
import { Games } from "src/components/templates/games"
import { Header } from "src/components/templates/header"

const GamesPage: NextPage = () => {
  return (
    <div className="h-screen overflow-auto bg-zinc-900">
      <Head>
        <title>Bolão da Copa Grão Direto</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <Header />

      <div className="container mx-auto">
        <Games />
      </div>

      <Footer />

    </div>
  )
}

export default GamesPage