import type { NextPage } from 'next'
import Head from 'next/head'

import { Header } from "../../components/templates/header"
import { Pickem } from "../../components/templates/pickem"

const PickemPage: NextPage = () => {
  return (
    <div className="h-screen overflow-auto bg-zinc-900">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <Pickem />
    </div>
  )
}

export default PickemPage