import * as Avatar from "@radix-ui/react-avatar"
import type { NextPage } from 'next'
import Head from 'next/head'
import Link from "next/link"

const Home: NextPage = () => {
  return (
    <div className="h-screen overflow-hidden bg-zinc-900">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className="px-6 bg-zinc-900 h-20 flex justify-between items-center border-b border-zinc-800">
        <h1 className="text-white text-lg">GG</h1>

        <div className="flex-auto flex justify-center">
          <ul className="flex gap-8 text-white uppercase font-semibold">
            <li><Link href="#"><a>Home</a></Link></li>
            <li><Link href="#"><a>Cronograma</a></Link></li>
            <li><Link href="#"><a>Bolão</a></Link></li>
          </ul>
        </div>

        <Avatar.Root className="bg-zinc-800 w-12 h-12 rounded-full">
          <Avatar.Image />
          <Avatar.Fallback  />
        </Avatar.Root>

      </header>
    </div>
  )
}

export default Home
